# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-23 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_name', models.CharField(max_length=20)),
                ('alternate_names', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('serves', models.PositiveSmallIntegerField()),
                ('prep_time', models.PositiveIntegerField()),
                ('cook_time', models.PositiveIntegerField()),
                ('ingredient_list', models.CharField(max_length=500)),
                ('instructions', models.TextField()),
                ('meal_type', models.CharField(choices=[('BRE', 'BREAKFAST'), ('LUN', 'LUNCH'), ('DIN', 'DINNER'), ('DES', 'DESERT'), ('SNA', 'SNACK')], default='DIN', max_length=3)),
                ('dish_type', models.CharField(choices=[('BRE', 'BREAKFAST'), ('LUN', 'LUNCH'), ('DIN', 'DINNER'), ('DES', 'DESERT'), ('SNA', 'SNACK')], default='VEG', max_length=3)),
                ('ingredients', models.ManyToManyField(to='recipes.Ingredient')),
            ],
        ),
    ]
