# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-23 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='alternate_names',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alternate Names'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='primary_name',
            field=models.CharField(max_length=20, verbose_name='Primary Name'),
        ),
    ]
