# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-23 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20170823_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='contributor',
            field=models.CharField(default='60 minutes', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='source',
            field=models.CharField(default='NYT', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='source_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='yeild',
            field=models.CharField(default='2 pizzas', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('BRE', 'BREAKFAST'), ('LUN', 'LUNCH'), ('DIN', 'DINNER'), ('DES', 'DESSERT'), ('SNA', 'SNACK')], default='DIN', max_length=3),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='serves',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
