# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-26 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20170823_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_text', models.CharField(max_length=50)),
                ('ammount', models.DecimalField(decimal_places=3, max_digits=4)),
                ('associated_recipe_slug', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('WGT', 'WEIGHT'), ('VOL', 'VOLUME'), ('CNT', 'COUNT')], default='CNT', max_length=3)),
                ('unit_name', models.CharField(max_length=20)),
                ('unit_name_plural', models.CharField(max_length=21)),
                ('unit_abbreviation', models.CharField(max_length=5)),
                ('unit_abbreviation_plural', models.CharField(max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='alternate_names',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='temp', max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='primary_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Primary Name'),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient_list',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='matched_ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Ingredient'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Unit'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_list',
            field=models.ManyToManyField(to='recipes.RecipeIngredient'),
        ),
    ]
