# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-30 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20170826_0357'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Ingredient Category')),
            ],
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='associated_recipe_slug',
            new_name='associated_recipe_title',
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='matched_ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Unit'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='recipes.IngredientCategory'),
        ),
    ]
