# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-30 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20170830_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='associated_recipe_title',
            new_name='associated_recipe_slug',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.ManyToManyField(to='recipes.IngredientCategory'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='matched_ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Ingredient'),
        ),
    ]
