# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-30 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20170830_0236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientcategory',
            options={'verbose_name_plural': 'Ingredient Categories'},
        ),
    ]
