# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-30 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20170830_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='alternate_names',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Alternate Names'),
        ),
    ]
