# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-30 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_ingredient_alternate_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='index',
            field=models.IntegerField(default=1, verbose_name='Ingredient Index'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe_text',
            field=models.CharField(max_length=100),
        ),
    ]
