# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-31 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20170830_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='ammount_text',
            field=models.CharField(default='none', max_length=150),
            preserve_default=False,
        ),
    ]
