# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-31 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_recipeingredient_ammount_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='ammount_text',
        ),
    ]
