# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-07 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_remove_recipeingredient_ammount_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='ammount',
            field=models.DecimalField(decimal_places=10, max_digits=14),
        ),
    ]
